<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Endereco extends \App\Entity\Endereco implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'cep', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'nrImovel', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'cidade', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'logradouro', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'complemento', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'coordenadas', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'bairro'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'cep', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'nrImovel', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'cidade', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'logradouro', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'complemento', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'coordenadas', '' . "\0" . 'App\\Entity\\Endereco' . "\0" . 'bairro'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Endereco $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep(): \App\Entity\Cep
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep(\App\Entity\Cep $cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrImovel(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrImovel', []);

        return parent::getNrImovel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrImovel(int $nrImovel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrImovel', [$nrImovel]);

        return parent::setNrImovel($nrImovel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade(): \App\Entity\Cidade
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade(\App\Entity\Cidade $cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogradouro(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogradouro', []);

        return parent::getLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogradouro(string $logradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogradouro', [$logradouro]);

        return parent::setLogradouro($logradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', []);

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento(string $complemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', [$complemento]);

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoordenadas(): \App\Entity\Coordenadas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoordenadas', []);

        return parent::getCoordenadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoordenadas(\App\Entity\Coordenadas $coordenadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoordenadas', [$coordenadas]);

        return parent::setCoordenadas($coordenadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro(string $bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
