<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Acesso extends \App\Entity\Acesso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'rota', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'GET', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'POST', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'PUT', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'DELETE'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'rota', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'GET', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'POST', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'PUT', '' . "\0" . 'App\\Entity\\Acesso' . "\0" . 'DELETE'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Acesso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getRota(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRota', []);

        return parent::getRota();
    }

    /**
     * {@inheritDoc}
     */
    public function setRota(string $rota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRota', [$rota]);

        return parent::setRota($rota);
    }

    /**
     * {@inheritDoc}
     */
    public function isGet(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isGet', []);

        return parent::isGet();
    }

    /**
     * {@inheritDoc}
     */
    public function setGet(bool $GET)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGet', [$GET]);

        return parent::setGet($GET);
    }

    /**
     * {@inheritDoc}
     */
    public function isPost(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPost', []);

        return parent::isPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosta(bool $POST)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosta', [$POST]);

        return parent::setPosta($POST);
    }

    /**
     * {@inheritDoc}
     */
    public function isPut(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPut', []);

        return parent::isPut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPut(bool $PUT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPut', [$PUT]);

        return parent::setPut($PUT);
    }

    /**
     * {@inheritDoc}
     */
    public function isDelete(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDelete', []);

        return parent::isDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelete(bool $DELETE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelete', [$DELETE]);

        return parent::setDelete($DELETE);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
